name: Build & Deploy SIGIC Nuxt Frontend (develop)

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build SIGIC Nuxt Frontend image (develop)
    runs-on: ${{ vars.IMAGE_NAME == 'sigic-nuxt-frontend' && fromJSON('["self-hosted", "build-develop", "sigic-nuxt-frontend"]') || fromJSON('["self-hosted", "deploy-develop", "geosuite-nuxt-frontend"]') }}
    environment: develop
    if: github.event_name == 'push'

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_GEOINTSIGIC_PAT }}" | docker login ghcr.io -u geointsigic --password-stdin

      - name: Set environment
        id: env
        run: |
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> "$GITHUB_OUTPUT"
          echo "NUXT_PUBLIC_BASE_URL=${{ vars.NUXT_PUBLIC_BASE_URL }}" >> "$GITHUB_OUTPUT"

      - name: Build & tag Docker image
        run: |
          docker build \
            -t ghcr.io/${{ vars.OWNER }}/${{ vars.IMAGE_NAME }}:develop \
            -t ghcr.io/${{ vars.OWNER }}/${{ vars.IMAGE_NAME }}:${GITHUB_SHA::7} \
            -f Dockerfile .

      - name: Push image
        run: |
          docker push ghcr.io/${{ vars.OWNER }}/${{ vars.IMAGE_NAME }}:develop
          docker push ghcr.io/${{ vars.OWNER }}/${{ vars.IMAGE_NAME }}:${GITHUB_SHA::7}

  deploy:
    name: Deploy SIGIC Nuxt frontend to dev server
    needs: build
    runs-on: ${{ vars.IMAGE_NAME == 'sigic-nuxt-frontend' && fromJSON('["self-hosted", "deploy-develop", "sigic-nuxt-frontend"]') || fromJSON('["self-hosted", "deploy-develop", "geosuite-nuxt-frontend"]') }}
    environment: develop
    if: github.event_name == 'push'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login to GHCR
        run: echo ${{ secrets.GHCR_GEOINTSIGIC_PAT }} | docker login ghcr.io -u geointsigic --password-stdin

      - name: Reemplazar imagen en docker-compose-idce.yml
        run: |
          sed -i "s|ghcr.io/${{ vars.OWNER }}/sigic-nuxt-frontend:.*|ghcr.io/${{ vars.OWNER }}/${{ vars.IMAGE_NAME }}:${GITHUB_SHA::7}|g" docker-compose-idce.yml

      - name: Escribir archivo .env
        run: |
          echo "NODE_ENV=production" >> .env
          echo "COMPOSE_PROJECT_NAME=${{ vars.COMPOSE_PROJECT_NAME }}" >> .env
          echo "NGINX_BASE_URL=${{ vars.NGINX_BASE_URL }}" >> .env
          echo "NUXT_PUBLIC_BASE_URL=${{ vars.NUXT_PUBLIC_BASE_URL }}" >> .env
          echo "NUXT_PUBLIC_GEONODE_URL=${{ vars.NUXT_PUBLIC_GEONODE_URL }}" >> .env
          echo "NUXT_PUBLIC_GEONODE_API=${{ vars.NUXT_PUBLIC_GEONODE_API }}" >> .env          
          echo "NUXT_PUBLIC_GEOSERVER_URL=${{ vars.NUXT_PUBLIC_GEOSERVER_URL }}" >> .env
          echo "NUXT_PUBLIC_IA_BACKEND_URL=${{ vars.NUXT_PUBLIC_IA_BACKEND_URL }}" >> .env
          echo "NUXT_PUBLIC_LEVANTAMIENTO_BACKEND_URL=${{ vars.NUXT_PUBLIC_LEVANTAMIENTO_BACKEND_URL }}" >> .env
          echo "NUXT_PUBLIC_DEFAULT_PAGE=${{ vars.NUXT_PUBLIC_DEFAULT_PAGE }}" >> .env
          echo "NUXT_PUBLIC_GEONODE_API_DEFAULT_FILTER=${{ vars.NUXT_PUBLIC_GEONODE_API_DEFAULT_FILTER }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_AUTH=${{ vars.NUXT_PUBLIC_ENABLE_AUTH }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_CATALOGO_VISTA=${{ vars.NUXT_PUBLIC_ENABLE_CATALOGO_VISTA }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_CATALOGO_CARGA=${{ vars.NUXT_PUBLIC_ENABLE_CATALOGO_CARGA }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_CONSULTA=${{ vars.NUXT_PUBLIC_ENABLE_CONSULTA }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_IAA=${{ vars.NUXT_PUBLIC_ENABLE_IAA }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_LEVANTAMIENTO=${{ vars.NUXT_PUBLIC_ENABLE_LEVANTAMIENTO }}" >> .env
          ECHO "NUXT_PUBLIC_ENABLE_MAPAS=${{ VARS.NUXT_PUBLIC_ENABLE_MAPAS }}" >> .ENV
          echo "NUXT_PUBLIC_ENABLE_ACERCA_DE=${{ vars.NUXT_PUBLIC_ENABLE_ACERCA_DE }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_GEOCONTENIDOS=${{ vars.NUXT_PUBLIC_ENABLE_GEOCONTENIDOS }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_GEOHISTORIAS=${{ vars.NUXT_PUBLIC_ENABLE_GEOHISTORIAS }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_TABLEROS=${{ vars.NUXT_PUBLIC_ENABLE_TABLEROS }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_PANORAMAS=${{ vars.NUXT_PUBLIC_ENABLE_PANORAMAS }}" >> .env
          echo "NUXT_PUBLIC_ENABLE_LANDING_BUILDER=${{ vars.NUXT_PUBLIC_ENABLE_LANDING_BUILDER }}" >> .env
          echo "NUXT_AUTH_ORIGIN=${{ vars.NUXT_AUTH_ORIGIN }}" >> .env
          echo "NUXT_PUBLIC_AUTH_BASE_URL=${{ vars.NUXT_PUBLIC_AUTH_BASE_URL }}" >> .env
          echo "KEYCLOAK_ISSUER=${{ vars.KEYCLOAK_ISSUER }}" >> .env
          echo "KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}" >> .env
          echo "KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}" >> .env
          echo "NUXT_PUBLIC_KEYCLOAK_ISSUER=${{ vars.NUXT_PUBLIC_KEYCLOAK_ISSUER }}" >> .env
          echo "NUXT_PUBLIC_KEYCLOAK_CLIENT_ID=${{ secrets.NUXT_PUBLIC_KEYCLOAK_CLIENT_ID }}" >> .env
          echo "NUXT_AUTH_SECRET=${{ secrets.NUXT_AUTH_SECRET }}" >> .env
          echo "NUXT_APP_BASE_URL=${{ vars.NUXT_APP_BASE_URL }}" >> .env
          echo "NUXT_PUBLIC_OLLAMA_MODEL=${{ vars.NUXT_PUBLIC_OLLAMA_MODEL }}" >> .env
          echo "SOCIALACCOUNT_OIDC_ID_TOKEN_ISSUER=${{ vars.SOCIALACCOUNT_OIDC_ID_TOKEN_ISSUER }}" >> .env
          echo "VIRTUAL_PORT=3000" >> .env

      - name: Docker Compose up
        run: |
          docker compose -f docker-compose-idce.yml down || true
          docker compose -f docker-compose-idce.yml up -d --force-recreate
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          COMPOSE_PROJECT_NAME: ${{ vars.COMPOSE_PROJECT_NAME }}
          NGINX_BASE_URL: ${{ vars.NGINX_BASE_URL }}
          NUXT_PUBLIC_BASE_URL: ${{ vars.NUXT_PUBLIC_BASE_URL }}
          NUXT_PUBLIC_GEONODE_URL: ${{ vars.NUXT_PUBLIC_GEONODE_URL }}
          NUXT_PUBLIC_GEONODE_API: ${{ vars.NUXT_PUBLIC_GEONODE_API }}
          NUXT_PUBLIC_GEOSERVER_URL: ${{ vars.NUXT_PUBLIC_GEOSERVER_URL }}
          NUXT_PUBLIC_IA_BACKEND_URL: ${{ vars.NUXT_PUBLIC_IA_BACKEND_URL }}
          NUXT_PUBLIC_LEVANTAMIENTO_BACKEND_URL: ${{ vars.NUXT_PUBLIC_LEVANTAMIENTO_BACKEND_URL }}
          NUXT_PUBLIC_DEFAULT_PAGE: ${{ vars.NUXT_PUBLIC_DEFAULT_PAGE }}
          NUXT_PUBLIC_GEONODE_API_DEFAULT_FILTER: ${{ vars.NUXT_PUBLIC_GEONODE_API_DEFAULT_FILTER }}
          NUXT_PUBLIC_ENABLE_AUTH: ${{ vars.NUXT_PUBLIC_ENABLE_AUTH }}
          NUXT_PUBLIC_ENABLE_CATALOGO_VISTA: ${{ vars.NUXT_PUBLIC_ENABLE_CATALOGO_VISTA }}
          NUXT_PUBLIC_ENABLE_CATALOGO_CARGA: ${{ vars.NUXT_PUBLIC_ENABLE_CATALOGO_CARGA }}
          NUXT_PUBLIC_ENABLE_CONSULTA: ${{ vars.NUXT_PUBLIC_ENABLE_CONSULTA }}
          NUXT_PUBLIC_ENABLE_IAA: ${{ vars.NUXT_PUBLIC_ENABLE_IAA }}
          NUXT_PUBLIC_ENABLE_LEVANTAMIENTO: ${{ vars.NUXT_PUBLIC_ENABLE_LEVANTAMIENTO }}
          NUXT_PUBLIC_ENABLE_MAPAS: ${{ vars.NNUXT_PUBLIC_ENABLE_MAPAS }}
          NUXT_PUBLIC_ENABLE_ACERCA_DE: ${NUXT_PUBLIC_ENABLE_ACERCA_DE}
          NUXT_PUBLIC_ENABLE_GEOCONTENIDOS: ${NUXT_PUBLIC_ENABLE_GEOCONTENIDOS}
          NUXT_PUBLIC_ENABLE_GEOHISTORIAS: ${NUXT_PUBLIC_ENABLE_GEOHISTORIAS}
          NUXT_PUBLIC_ENABLE_TABLEROS: ${NUXT_PUBLIC_ENABLE_TABLEROS}
          NUXT_PUBLIC_ENABLE_PANORAMAS: ${NUXT_PUBLIC_ENABLE_PANORAMAS}
          NUXT_PUBLIC_ENABLE_LANDING_BUILDER: ${NUXT_PUBLIC_ENABLE_LANDING_BUILDER}
          NUXT_AUTH_ORIGIN: ${{ vars.NUXT_AUTH_ORIGIN }}
          NUXT_PUBLIC_AUTH_BASE_URL: ${{ vars.NUXT_PUBLIC_AUTH_BASE_URL }}
          KEYCLOAK_ISSUER: ${{ vars.KEYCLOAK_ISSUER }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          NUXT_PUBLIC_KEYCLOAK_ISSUER: ${{ vars.NUXT_PUBLIC_KEYCLOAK_ISSUER }}
          NUXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${{ secrets.NUXT_PUBLIC_KEYCLOAK_CLIENT_ID }}
          NUXT_AUTH_SECRET: ${{ secrets.NUXT_AUTH_SECRET }}
          NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL }}
          NUXT_PUBLIC_OLLAMA_MODEL: ${{ vars.NUXT_PUBLIC_OLLAMA_MODEL }}
          SOCIALACCOUNT_OIDC_ID_TOKEN_ISSUER: ${{ vars.SOCIALACCOUNT_OIDC_ID_TOKEN_ISSUER }}
          VIRTUAL_PORT: ${{ vars.VIRTUAL_PORT }}
